//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCAdminCustomMods.Tasks.MinecraftModpacks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PythonScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PythonScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCAdminCustomMods.Tasks.MinecraftModpacks.PythonScripts", typeof(PythonScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import urllib, urllib2, json, clr, os, zipfile, shutil, time, random, inspect, re, csv, time
        ///from xml.etree.ElementTree import parse
        ///clr.AddReference(&apos;RestSharp&apos;)
        ///from RestSharp import RestClient, RestRequest
        ///from System.Diagnostics import Process
        ///from System.IO import File
        ///clr.AddReference(&apos;TCAdmin.SDK&apos;)
        ///clr.AddReference(&apos;TCAdmin.GameHosting.SDK&apos;)
        ///from TCAdmin.GameHosting.SDK.Objects import CustomCmdLine, GameVariableConfig
        ///from TCAdmin.SDK.Scripting import ScriptUtility
        ///from TCAdmin.SDK.Misc imp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MinecraftModpack_Curseforge {
            get {
                return ResourceManager.GetString("MinecraftModpack-Curseforge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import urllib, urllib2, json, clr, os, zipfile, shutil, time, random, inspect, re
        ///clr.AddReference(&apos;RestSharp&apos;)
        ///from RestSharp import RestClient, RestRequest
        ///from System.Diagnostics import Process
        ///from System.IO import File
        ///clr.AddReference(&apos;TCAdmin.SDK&apos;)
        ///clr.AddReference(&apos;TCAdmin.GameHosting.SDK&apos;)
        ///from TCAdmin.GameHosting.SDK.Objects import CustomCmdLine, GameVariableConfig
        ///from TCAdmin.SDK.Scripting import ScriptUtility
        ///from TCAdmin.SDK.Misc import CompressionTools
        ///from System import Version
        ///fr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MinecraftModpack_FTB {
            get {
                return ResourceManager.GetString("MinecraftModpack-FTB", resourceCulture);
            }
        }
    }
}
